export const slides = [
  {
    id: 1,
    type: "cover",
    emoji: "🍳",
    title: "中層開發迴圈",
    subtitle: "Chapter 15 — 多代理 AI 協作實戰",
    author: "讀書心得筆記",
    tagline: "你是主廚，AI 是你的副主廚團隊",
    gradient: "linear-gradient(135deg, #134e5e 0%, #71b280 100%)",
  },
  {
    id: 2,
    type: "concept",
    emoji: "🧭",
    title: "核心比喻：廚房模型",
    headline: "主廚 vs 副主廚",
    description: "你是決策者，AI 代理是執行者",
    detail:
      "副主廚不會讀心術——你必須給出清楚、精準的指令。就像高級廚房：主廚設計菜單、把關品質，副主廚負責執行每道工序。AI 代理再厲害，也需要你明確告訴它「絕對要」和「絕對不要」做什麼。",
    math: "開發者（主廚）＋ AI 代理團隊（副主廚）",
    gradient: "linear-gradient(135deg, #134e5e 0%, #71b280 100%)",
  },
  {
    id: 3,
    type: "overview",
    emoji: "🗂️",
    title: "本章三大核心機制",
    subtitle: "中層開發迴圈的完整架構",
    laws: [
      { icon: "🛡️", num: "1", label: "預防措施", eng: "Prevention" },
      { icon: "🔍", num: "2", label: "偵測機制", eng: "Detection" },
      { icon: "🔧", num: "3", label: "修正方案", eng: "Remediation" },
      { icon: "⚡", num: "+", label: "投資自動化", eng: "Automation" },
    ],
    gradient: "linear-gradient(135deg, #1d4350 0%, #a43931 100%)",
  },

  // ── PREVENTION ──
  {
    id: 4,
    type: "law",
    emoji: "🛡️",
    lawNum: "機制一｜預防",
    title: "建立黃金守則",
    subtitle: "永遠適用、不隨情況改變的規則",
    points: [
      "🚫 絕不使用全域變數",
      "🔑 絕不把金鑰（API key）放入版本控制",
      "🛠️ 必須使用機密管理工具",
      "🏗️ 避免深層巢狀狀態圖式",
      "❌ 在強型別語言中避免使用萬用型別（如 `any`）",
    ],
    example: "💡 黃金守則越小越精準，AI 越容易遵守——清單從 28 條刪到 9 條",
    gradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)",
  },
  {
    id: 5,
    type: "what",
    emoji: "📋",
    title: "AGENTS.md 記憶檔案",
    description:
      "把規則寫進 AGENTS.md，讓每次對話都從相同基礎出發。AI 代理已經制度化為現在的 AI，AGENTS.md 的規則能讓它不斷知道你的獨特規則，提醒它不要再犯同樣的錯。",
    points: [
      "📝 Markdown 格式，放在專案根目錄",
      "🔄 每次對話系統自動插入上下文開頭",
      "🧠 長期可使用記憶資料庫（如 Mem0）",
      "🎯 記憶分類：黃金守則、AI 合作規則、專案背景",
      "⚠️ 規則太多反而失效——保持精簡，AI 更容易遵守",
    ],
    gradient: "linear-gradient(135deg, #2c3e50 0%, #4ca1af 100%)",
  },
  {
    id: 6,
    type: "concept",
    emoji: "🧠",
    title: "管理 AI 的上下文視窗",
    headline: "上下文是 AI 的工作記憶",
    description: "AI 在多數情況下會用 20～50% 的上下文存放規則",
    detail:
      "上下文視窗越大，AI 的注意力越容易被稀釋。你的指示、規則、程式碼都在搶同一塊空間。定期清除上下文、重新整理對話，是讓 AI 保持在最佳狀態的基本功。",
    math: "上下文越滿 → AI 注意力越分散 → 品質下降",
    gradient: "linear-gradient(135deg, #373b44 0%, #4286f4 100%)",
  },
  {
    id: 7,
    type: "mindset",
    emoji: "🤖",
    title: "不要對抗 AI 的天性",
    comparisons: [
      { before: "❌ 強迫用 Svelte / Clojure", after: "✅ 選 React 等訓練資料豐富的框架" },
      { before: "❌ 用深層巢狀型別結構", after: "✅ 保持程式碼扁平、清晰" },
      { before: "❌ 讓 AI 記住所有細節", after: "✅ 都寫進 AGENTS.md 讓它查閱" },
      { before: "❌ 一次塞超長指令", after: "✅ 精簡指令 + 頻繁短對話迭代" },
    ],
    gradient: "linear-gradient(135deg, #0f2027 0%, #2c5364 100%)",
  },
  {
    id: 8,
    type: "benefit",
    emoji: "💰",
    title: "免費模型與成本現實",
    headline: "Token 成本正在快速下降",
    points: [
      "📉 開源（OSS）模型能力持續提升，免費選項越來越強",
      "🔄 Token 成本每年大幅降低，多代理成本已可負擔",
      "💡 Steve 同時跑 5 個代理，每天成本僅約 40 美元",
      "⚠️ 「重新檢查」會消耗更多 token，但長遠值得投資",
      "🔮 未來：高品質模型費用將接近零，多代理將成標準",
    ],
    example: "💡 現在就開始練習多代理協作，未來才不會被淘汰",
    gradient: "linear-gradient(135deg, #11998e 0%, #38ef7d 100%)",
  },

  // ── MULTI-AGENT ──
  {
    id: 9,
    type: "tools",
    emoji: "👥",
    title: "同時與多個 AI 代理協作",
    tools: [
      { icon: "🔀", name: "分離（Separation）", desc: "各代理處理不同模組，用獨立 Git branch 工作" },
      { icon: "🧩", name: "解耦（Decoupling）", desc: "模組間有明確介面，一個代理出錯不連鎖污染" },
      { icon: "🔁", name: "平行執行", desc: "代理 A 忙碌時，你已在引導代理 B 進行另一個任務" },
      { icon: "🏗️", name: "明確的介面", desc: "各元件之間要有清楚定義的邊界，避免合併衝突" },
    ],
    gradient: "linear-gradient(135deg, #1a1a2e 0%, #302b63 100%)",
  },
  {
    id: 10,
    type: "law",
    emoji: "🍽️",
    title: "砧板污染：最危險的多代理陷阱",
    subtitle: "切了生肉再切蔬菜，就是交叉污染",
    points: [
      "⚠️ 共用 port、資料庫、檔案、repo 都是污染來源",
      "🔌 MCP 伺服器的 proxy 層也可能造成衝突（race condition）",
      "🌀 平行執行 2 個代理時，最好以「步驟為序」執行",
      "📦 解法：每個代理有完全獨立的工作環境",
      "🔐 用互斥機制（mutual exclusion）管理共用資源",
    ],
    example: "💡 同一個 port 只能有一個代理用——否則兩個代理都會悄悄失敗",
    gradient: "linear-gradient(135deg, #c94b4b 0%, #4b134f 100%)",
  },
  {
    id: 11,
    type: "what",
    emoji: "🧑‍🍳",
    title: "在你忙碌時讓 AI 工作",
    description:
      "你不需要一直盯著 AI。讓一個代理執行任務時，你去引導另一個代理，等第一個完成再切回來——就像廚房主廚同時掌管多個爐台，不是守著一個鍋子傻等。",
    points: [
      "🔄 要求 AI 自我檢查：重新執行所有測試、語法檢查",
      "📋 讓 AI 跑「find and fix a bug」清單（OpenAI Codex 做法）",
      "🧹 清理環境：移除暫存檔、確認未追蹤的檔案都已處理",
      "📝 要求 AI 備份一份 Markdown 摘要，記錄完成了什麼",
      "✅ Claude Code 會「像人類一樣」回報——通常 2～3 次迭代後改善",
    ],
    gradient: "linear-gradient(135deg, #134e5e 0%, #71b280 100%)",
  },

  // ── DETECTION ──
  {
    id: 12,
    type: "law",
    emoji: "🔍",
    lawNum: "機制二｜偵測",
    title: "偵測機制：早期預警系統",
    subtitle: "比起修補，早期偵測的成本小 9 倍",
    points: [
      "🚨 系統性偵測：AI 代理出現衝突要即時知道",
      "🧪 要求 AI 報告所有測試結果，不只說「完成了」",
      "📊 Steve 的 FAAFO 自我審查法：效率提升 15～20%",
      "🔒 衝突偵測：多代理共用資源需要互斥機制",
      "🐛 Dan Sturtevant 統計：在複雜系統修 bug 的成本多出 9 倍",
    ],
    example: "💡 實踐：叫 AI 檢查半成品的結果，「完成的建議」無法執行的也算不到分",
    gradient: "linear-gradient(135deg, #4b1248 0%, #f10711 100%)",
  },
  {
    id: 13,
    type: "takeaway",
    emoji: "😱",
    title: "Gene 的血淚教訓：AI 生成的恐懼怪物",
    quotes: [
      {
        text: "程式碼已經是 3,000 行的巨獸，大圖式、沒有函式、沒有模組邊界，Gene 完全看不懂。",
        en: "The code became a 3,000-line monster — no functions, no module boundaries. Gene couldn't understand any of it.",
      },
      {
        text: "每一步都像在拆炸彈，修好一個地方就炸出兩個新的問題，UI 代理讓整個系統變成 Escher 的畫作。",
        en: "Every step felt like defusing a bomb — fix one thing, two more explode. The UI agent made the system an Escher drawing.",
      },
      {
        text: "解決這類問題的最簡單方法，就是絕對、永遠不要陷入 AI 生成的閘門程式碼裡。",
        en: "The simplest way to solve this is to absolutely never get trapped inside AI-generated gatekeeping code.",
      },
    ],
    gradient: "linear-gradient(135deg, #1a1a2e 0%, #f10711 100%)",
  },
  {
    id: 14,
    type: "tools",
    emoji: "⚔️",
    title: "廚師過多：代理間的爭執資源",
    tools: [
      { icon: "🗄️", name: "共用資料庫", desc: "多個代理同時讀寫，產生難追蹤的 race condition" },
      { icon: "📁", name: "共用檔案 / 分支", desc: "同一個 branch 被兩個代理同時修改，合併必爆" },
      { icon: "🔌", name: "共用 port / 服務", desc: "port 已被佔用，另一個代理靜悄悄地失敗" },
      { icon: "🤖", name: "共用 MCP 服務器", desc: "代理競爭同一個 proxy，造成不可預測的互動" },
    ],
    gradient: "linear-gradient(135deg, #2c3e50 0%, #e74c3c 100%)",
  },

  // ── REMEDIATION ──
  {
    id: 15,
    type: "law",
    emoji: "🔧",
    lawNum: "機制三｜修正",
    title: "修正方案：閃光彈法",
    subtitle: "AI 跑偏了，先退後再前進",
    points: [
      "💡 閃光彈原則：集中但不完整的方案 > 無法通過任何測試",
      "🚫 永遠不要讓 AI 在錯誤方向上繼續修補再修補",
      "🔙 從第 12 章的災害復原層退到穩定狀態再重來",
      "🪓 仔細觀察後，用最小的介入找到最安心的出路",
      "📊 Steve：發現 AI 問題後，不是馬上叫它重寫，而是先理解",
    ],
    example: "💡 Gene 做法：fork 一個 shell，把 `ls -a` pipe 給 `llm` 工具，5 分鐘出分析結果",
    gradient: "linear-gradient(135deg, #136a8a 0%, #267871 100%)",
  },
  {
    id: 16,
    type: "what",
    emoji: "🌟",
    title: "閃光彈法實戰案例",
    description:
      "Steve 遇到 Ruby 腳本要移植到 Kotlin 的阻礙，AI 一直找不到正確的 Gradle 設定參數。他沒有繼續在同一個問題上打轉——他改用閃光彈法：一次交接一個最小問題，找到可執行的出路後，再繼續往前推進。",
    points: [
      "🔍 先用 AI 分析程式碼的怪異和奇特案例",
      "🧩 建立自動化測試案例，確保覆蓋率",
      "🔄 改進後驗證：是否破壞了任何現有功能",
      "✅ 完成後立即測試——「改好了一點！」再繼續下一個",
      "🚀 Simon Willison 的 `llm` 指令工具讓整個流程更高效",
    ],
    gradient: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
  },

  // ── AUTOMATION ──
  {
    id: 17,
    type: "benefit",
    emoji: "⚡",
    title: "蒼利刀具：投資工作流程自動化",
    headline: "把那些「佔用你意識」的工作交給機器",
    points: [
      "🔁 你的意識流程在 vibe coding 時會被優先佔領",
      "😫 微小錯誤增加、編輯器與聊天工具頻繁切換成瓶頸",
      "🕐 每次 context switch 都需要重新暖機——時間成本驚人",
      "🤖 把重複工作自動化，每天省下的時間快速累積",
      "📈 Gene 把對話輸入自動化後，從每隔幾分鐘啟動一次到不超過一秒",
    ],
    example: "💡 Steve 的 Android bug 報告：原本 3 小時/月，自動化後縮到幾分鐘",
    gradient: "linear-gradient(135deg, #11998e 0%, #38ef7d 100%)",
  },
  {
    id: 18,
    type: "concept",
    emoji: "🎲",
    title: "選擇權（Optionality）的力量",
    headline: "同時跑多條路，選最好的那條",
    description: "FAAFO 框架中的 σ（sigma）—— 選擇空間",
    detail:
      "OpenAI Jobs Report 引用的研究指出：在工作流程自動化後，你可以同時平行探索多種方案。Gene 的自動化把探索時間「t」從 3 分鐘縮到 1 分鐘，平行生成量增加 40 倍，選到最佳結果的機率就提高了 120 倍。",
    math: "NK/t × σ = FAAFO 的選擇能力",
    gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
  },
  {
    id: 19,
    type: "mindset",
    emoji: "📐",
    title: "FAAFO 公式：選擇權的四個參數",
    comparisons: [
      { before: "N＝可並行的試驗量", after: "越多平行代理，N 越大" },
      { before: "K＝可執行的試驗數", after: "自動化測試越多，K 越高" },
      { before: "t＝每次試驗的時間", after: "工具越快，t 越小" },
      { before: "σ＝不確定性與選擇空間", after: "vibe coding 讓 σ 大幅提升" },
    ],
    gradient: "linear-gradient(135deg, #1d4350 0%, #a43931 100%)",
  },
  {
    id: 20,
    type: "end",
    emoji: "🌟",
    title: "本章小結：中層迴圈六把鑰匙",
    steps: [
      "🛡️ 記錄黃金守則進 AGENTS.md，精簡到 AI 能真正遵守",
      "🧑‍🍳 把 AI 當副主廚——給清楚指令、不要讓它讀心",
      "🏗️ 架構解耦，各代理有獨立工作環境避免砧板污染",
      "👥 擁抱多代理平行協作，利用 context switch 填滿等待時間",
      "💥 AI 跑偏時用閃光彈法——退回穩定點，最小步驟重進攻",
      "⚡ 投資自動化工作流程，累積長期選擇權（σ）",
    ],
    closing: "中層開發迴圈，是 vibe coding 能走多遠的關鍵 🍳",
    gradient: "linear-gradient(135deg, #134e5e 0%, #71b280 100%)",
  },
];
