export const slides = [
  {
    id: 1,
    type: "cover",
    emoji: "🎵",
    title: "Vibe Coding",
    subtitle: "用 AI 對話寫程式的新方式",
    author: "The Future of Development",
    tagline: "說出你的想法，AI 幫你實現",
    gradient: "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)",
  },
  {
    id: 2,
    type: "what",
    emoji: "🤖",
    title: "什麼是 Vibe Coding？",
    description:
      "Vibe Coding 是一種以自然語言為主導的程式開發方式，開發者用對話描述需求，讓 AI 生成、修改、解釋程式碼。",
    points: [
      "💬 用中文或英文描述你想要的功能",
      "🔄 與 AI 反覆對話、迭代改進",
      "🎯 聚焦在「要什麼」而非「怎麼寫」",
      "⚡ 數分鐘內完成過去需要數小時的任務",
    ],
    gradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
  },
  {
    id: 3,
    type: "benefit",
    emoji: "🚀",
    title: "好處一：極速開發",
    headline: "開發速度提升 10 倍",
    points: [
      "⏱️ 幾分鐘建立完整功能模組",
      "🔁 快速原型驗證想法",
      "📋 自動生成樣板程式碼（boilerplate）",
      "🧪 一鍵產生測試案例",
    ],
    example: "💡 例：「幫我建一個帶搜尋功能的使用者列表頁面」→ 30 秒完成",
    gradient: "linear-gradient(135deg, #f953c6 0%, #b91d73 100%)",
  },
  {
    id: 4,
    type: "benefit",
    emoji: "🧠",
    title: "好處二：降低心智負擔",
    headline: "把腦力用在真正重要的事",
    points: [
      "😌 不需要記憶 API 細節與語法",
      "📚 AI 即時解釋不熟悉的程式概念",
      "🔍 自動找出錯誤原因並修復",
      "🗺️ 讓你專注在架構設計與產品邏輯",
    ],
    example: "💡 例：「這段 SQL 為什麼會 N+1？幫我修掉」",
    gradient: "linear-gradient(135deg, #4776e6 0%, #8e54e9 100%)",
  },
  {
    id: 5,
    type: "benefit",
    emoji: "🌱",
    title: "好處三：降低學習門檻",
    headline: "非工程師也能創造產品",
    points: [
      "🎨 設計師可以自己實現互動效果",
      "📊 產品經理可以快速做出 Demo",
      "🏢 業務人員可以建立自動化工具",
      "👶 初學者可以跳過枯燥的語法入門",
    ],
    example: "💡 例：設計師說「幫我做一個拖曳排序的卡片」→ 直接完成",
    gradient: "linear-gradient(135deg, #11998e 0%, #38ef7d 100%)",
  },
  {
    id: 6,
    type: "benefit",
    emoji: "🔍",
    title: "好處四：即時學習與成長",
    headline: "寫程式 = 同時在學程式",
    points: [
      "📖 AI 主動解釋生成的程式碼",
      "🤔 可以問「為什麼這樣寫？」",
      "🔄 看到好的寫法後馬上吸收",
      "📈 在做中學，學習效率大幅提升",
    ],
    example: "💡 例：「你用了 useCallback，可以解釋為什麼嗎？」",
    gradient: "linear-gradient(135deg, #f6d365 0%, #fda085 100%)",
  },
  {
    id: 7,
    type: "benefit",
    emoji: "♻️",
    title: "好處五：輕鬆重構與維護",
    headline: "舊程式碼不再是噩夢",
    points: [
      "🧹 一鍵重構混亂的舊程式",
      "📝 自動補充遺漏的文件與註解",
      "🔒 快速審查安全性問題",
      "🌐 輕鬆跨語言移植程式邏輯",
    ],
    example: "💡 例：「把這段 JavaScript 重寫成 TypeScript，加上型別」",
    gradient: "linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)",
  },
  {
    id: 8,
    type: "tools",
    emoji: "🛠️",
    title: "主流 Vibe Coding 工具",
    tools: [
      { icon: "⚡", name: "Claude Code", desc: "終端機 AI 助手，直接操作檔案與指令" },
      { icon: "🖥️", name: "Cursor", desc: "AI 原生 IDE，深度整合 GPT / Claude" },
      { icon: "🌊", name: "Windsurf", desc: "Codeium 出品，具備 Cascade AI 代理" },
      { icon: "🤖", name: "GitHub Copilot", desc: "VS Code 整合，微軟 + OpenAI 合作" },
      { icon: "💬", name: "v0 / Bolt", desc: "一句話生成完整前端 UI 專案" },
    ],
    gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
  },
  {
    id: 9,
    type: "mindset",
    emoji: "💡",
    title: "Vibe Coding 心態轉變",
    comparisons: [
      { before: "❌ 背誦所有語法", after: "✅ 描述想要的結果" },
      { before: "❌ 從頭開始打程式碼", after: "✅ 引導 AI 迭代改進" },
      { before: "❌ 獨自 Debug 數小時", after: "✅ 貼給 AI 秒速排查" },
      { before: "❌ 害怕接觸新技術", after: "✅ AI 帶你快速上手" },
    ],
    gradient: "linear-gradient(135deg, #30cfd0 0%, #330867 100%)",
  },
  {
    id: 10,
    type: "end",
    emoji: "🎯",
    title: "開始你的 Vibe Coding",
    steps: [
      "✅ 選一個你想解決的問題",
      "✅ 用自然語言描述功能需求",
      "✅ 與 AI 對話、迭代、改進",
      "✅ 理解 AI 生成的程式碼",
    ],
    closing: "想法就是你的程式碼 🎵",
    gradient: "linear-gradient(135deg, #fc466b 0%, #3f5efb 100%)",
  },
];
