export const slides = [
  {
    id: 1,
    type: "cover",
    emoji: "⚛️",
    title: "原子習慣",
    subtitle: "Atomic Habits",
    author: "James Clear 著",
    tagline: "微小改變，帶來巨大成果",
    gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
  },
  {
    id: 2,
    type: "author",
    emoji: "👨‍💼",
    title: "關於作者",
    name: "James Clear",
    points: [
      "🌍 全球知名習慣研究者與作家",
      "📧 每週電子報訂閱人數超過 100 萬",
      "📚 《原子習慣》銷量突破 1500 萬冊",
      "🎤 企業演講嘉賓，分享習慣科學",
      "💡 專注於決策、習慣與持續改善",
    ],
    gradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
  },
  {
    id: 3,
    type: "concept",
    emoji: "📈",
    title: "核心概念",
    headline: "每天進步 1%",
    description: "365 天後，你將進步 37 倍",
    detail:
      "微小的改變看似毫不起眼，但長期累積的複利效應，將帶來令人驚嘆的巨大成果。",
    math: "1.01³⁶⁵ ≈ 37.78",
    gradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
  },
  {
    id: 4,
    type: "overview",
    emoji: "🔑",
    title: "行為改變四大法則",
    subtitle: "讓好習慣自動運作",
    laws: [
      { icon: "👁️", num: "1", label: "讓它顯而易見", eng: "Make it Obvious" },
      { icon: "🤩", num: "2", label: "讓它有吸引力", eng: "Make it Attractive" },
      { icon: "⚡", num: "3", label: "讓它輕而易舉", eng: "Make it Easy" },
      { icon: "🎉", num: "4", label: "讓它令人愉悅", eng: "Make it Satisfying" },
    ],
    gradient: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)",
  },
  {
    id: 5,
    type: "law",
    emoji: "👁️",
    lawNum: "第一法則",
    title: "讓它顯而易見",
    subtitle: "Make it Obvious",
    points: [
      "📋 記錄習慣清單，意識現有行為",
      "📍 實施意圖（時間 + 地點 = 行動）",
      "🔗 習慣堆疊：把新習慣接在舊習慣後",
      "🖼️ 設計環境，讓提示顯而易見",
    ],
    example: "💡 範例：把維他命放在早餐桌上",
    gradient: "linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)",
  },
  {
    id: 6,
    type: "law",
    emoji: "🤩",
    lawNum: "第二法則",
    title: "讓它有吸引力",
    subtitle: "Make it Attractive",
    points: [
      "🎯 誘惑捆綁：想做的事 + 應做的事",
      "👥 加入擁有共同目標的文化群體",
      "🧠 改寫心態：我必須做 → 我可以做",
      "🏆 預期獎勵激活大腦的渴望迴路",
    ],
    example: "💡 範例：只有運動時才能看喜歡的影集",
    gradient: "linear-gradient(135deg, #fd7943 0%, #fddb92 100%)",
  },
  {
    id: 7,
    type: "law",
    emoji: "⚡",
    lawNum: "第三法則",
    title: "讓它輕而易舉",
    subtitle: "Make it Easy",
    points: [
      "📉 減少習慣的執行阻力",
      "⏱️ 兩分鐘法則：新習慣僅需兩分鐘",
      "🛠️ 預備環境，降低行動門檻",
      "🔁 重複是形成習慣的關鍵",
    ],
    example: "💡 範例：睡前把運動服放在床邊",
    gradient: "linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)",
  },
  {
    id: 8,
    type: "law",
    emoji: "🎉",
    lawNum: "第四法則",
    title: "讓它令人愉悅",
    subtitle: "Make it Satisfying",
    points: [
      "🏅 立即獎勵自己，強化正向回饋",
      "📊 習慣追蹤器，視覺化進度",
      "🔥 不中斷連勝，保持動力",
      "🤝 找習慣夥伴，建立外部問責",
    ],
    example: "💡 範例：完成閱讀後在日曆打勾",
    gradient: "linear-gradient(135deg, #f6d365 0%, #fda085 100%)",
  },
  {
    id: 9,
    type: "loop",
    emoji: "🔄",
    title: "習慣迴路",
    subtitle: "The Habit Loop",
    steps: [
      { icon: "🎯", label: "提示 Cue", desc: "觸發行為的信號" },
      { icon: "💭", label: "渴望 Craving", desc: "想要改變的動機" },
      { icon: "⚙️", label: "回應 Response", desc: "實際執行的習慣" },
      { icon: "🏆", label: "獎勵 Reward", desc: "滿足渴望的結果" },
    ],
    note: "打破壞習慣：讓它不明顯、無吸引力、困難、不愉悅",
    gradient: "linear-gradient(135deg, #30cfd0 0%, #330867 100%)",
  },
  {
    id: 10,
    type: "takeaway",
    emoji: "🌟",
    title: "核心金句",
    quotes: [
      {
        text: "你不會提升到目標的水準，你會下降到系統的水準。",
        en: "You do not rise to the level of your goals, you fall to the level of your systems.",
      },
      {
        text: "每一個行動都是投票給你想成為的那種人。",
        en: "Every action you take is a vote for the type of person you wish to become.",
      },
      {
        text: "習慣不會限制你的自由，習慣創造自由。",
        en: "Habits do not restrict freedom. They create it.",
      },
    ],
    gradient: "linear-gradient(135deg, #667eea 0%, #f5576c 100%)",
  },
  {
    id: 11,
    type: "end",
    emoji: "🚀",
    title: "開始你的原子習慣",
    steps: [
      "✅ 選一個你想建立的習慣",
      "✅ 讓它顯而易見、有吸引力",
      "✅ 從最小版本開始執行",
      "✅ 追蹤進度，給自己獎勵",
    ],
    closing: "微小的開始，巨大的改變 🌱",
    gradient: "linear-gradient(135deg, #11998e 0%, #38ef7d 100%)",
  },
];
